name: Build and deploy Node.js app to Azure Web App - profelecghibli

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build (if applicable)
        run: npm run build --if-present

      - name: Zip app
        run: zip -r app.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7BDF713923DF408BBC365A499147BD56 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DCE0373A41CF45EC91F4DCD4A94A0C36 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4E0EEAB8E43844EBBD42876B75D9D3CE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ghibliwebapp'  # double check this matches your App Service name
          slot-name: 'Production'
          package: app.zip
